import React from 'react';
import {
  Folder,
  Hash,
  Calendar,
  BookOpen,
  Briefcase,
  Target,
  Home,
  User,
  Settings,
  Star,
  Heart,
  Coffee,
  Code,
  Palette,
  Music,
  Camera,
  Globe,
  ShoppingCart,
  Zap,
  Lightbulb,
  Rocket,
  Shield,
  Trophy,
  Flag,
  Clock,
  MapPin,
  Phone,
  Mail,
  MessageCircle,
  Check,
  X,
  Plus,
  Minus,
  Edit,
  Trash2,
  Save,
  Download,
  Upload,
  Search,
  Filter,
  Grid,
  List,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  Key,
  Bell,
  Volume2,
  VolumeX,
  Play,
  Pause,
  Square,
  SkipBack,
  SkipForward,
  Repeat,
  Shuffle,
  Maximize,
  Minimize,
  Move,
  Copy,
  Clipboard,
  Link,
  ExternalLink,
  Share,
  Image,
  File,
  FileText,
  Archive,
  Package,
  Box,
  Layers,
  Database,
  Server,
  Cloud,
  Wifi,
  WifiOff,
  Bluetooth,
  Battery,
  Cpu,
  HardDrive,
  Monitor,
  Smartphone,
  Tablet,
  Laptop,
  Mouse,
  Keyboard,
  Headphones,
  Mic,
  MicOff,
  Speaker,
  Printer,
  Tv,
  Radio,
  Car,
  Bike,
  Bus,
  Train,
  Plane,
  Ship,
  Truck,
  Fuel,
  Navigation,
  Compass,
  Map,
  Route,
  Building,
  TreePine,
  Mountain,
  Sun,
  Moon,
  CloudRain,
  CloudSnow,
  CloudLightning,
  Thermometer,
  Wind,
  Umbrella,
  Snowflake,
  Sunrise,
  Sunset,
  Activity,
  BarChart,
  BarChart2,
  BarChart3,
  PieChart,
  LineChart,
  TrendingUp,
  TrendingDown,
  DollarSign,
  CreditCard,
  Coins,
  Wallet,
  Receipt,
  Calculator,
  Percent,
  Award,
  Crown,
  Gift,
  Cake,
  Wine,
  Pizza,
  Apple,
  Leaf,
  Flower,
  Flower2,
  Bug,
  Fish,
  Bird,
  Cat,
  Dog
} from 'lucide-react';

// Define the icon mapping type
export type IconName = string;

// Icon mapping object
export const iconMap: Record<string, React.ComponentType<{ size?: number; className?: string; style?: React.CSSProperties }>> = {
  // Default and common icons
  'folder': Folder,
  'hash': Hash,
  'calendar': Calendar,
  'book': BookOpen,
  'briefcase': Briefcase,
  'target': Target,
  'home': Home,
  'user': User,
  'settings': Settings,
  'star': Star,
  'heart': Heart,
  'coffee': Coffee,
  'code': Code,
  'palette': Palette,
  'music': Music,
  'camera': Camera,
  'globe': Globe,
  'shopping': ShoppingCart,
  'zap': Zap,
  'lightbulb': Lightbulb,
  'rocket': Rocket,
  'shield': Shield,
  'trophy': Trophy,
  'flag': Flag,
  'clock': Clock,
  'map-pin': MapPin,
  'phone': Phone,
  'mail': Mail,
  'message': MessageCircle,

  // Actions
  'check': Check,
  'x': X,
  'plus': Plus,
  'minus': Minus,
  'edit': Edit,
  'trash': Trash2,
  'save': Save,
  'download': Download,
  'upload': Upload,
  'search': Search,
  'filter': Filter,
  'grid': Grid,
  'list': List,
  'eye': Eye,
  'eye-off': EyeOff,
  'lock': Lock,
  'unlock': Unlock,
  'key': Key,
  'bell': Bell,

  // Media
  'volume': Volume2,
  'volume-off': VolumeX,
  'play': Play,
  'pause': Pause,
  'stop': Square,
  'skip-back': SkipBack,
  'skip-forward': SkipForward,
  'repeat': Repeat,
  'shuffle': Shuffle,

  // Layout
  'maximize': Maximize,
  'minimize': Minimize,
  'move': Move,
  'copy': Copy,
  'clipboard': Clipboard,
  'link': Link,
  'external-link': ExternalLink,
  'share': Share,

  // Files
  'image': Image,
  'file': File,
  'file-text': FileText,
  'archive': Archive,
  'package': Package,
  'box': Box,
  'layers': Layers,

  // Tech
  'database': Database,
  'server': Server,
  'cloud': Cloud,
  'wifi': Wifi,
  'wifi-off': WifiOff,
  'bluetooth': Bluetooth,
  'battery': Battery,
  'cpu': Cpu,
  'hard-drive': HardDrive,
  'monitor': Monitor,
  'smartphone': Smartphone,
  'tablet': Tablet,
  'laptop': Laptop,
  'mouse': Mouse,
  'keyboard': Keyboard,
  'headphones': Headphones,
  'mic': Mic,
  'mic-off': MicOff,
  'speaker': Speaker,
  'printer': Printer,
  'tv': Tv,
  'radio': Radio,

  // Transport
  'car': Car,
  'bike': Bike,
  'bus': Bus,
  'train': Train,
  'plane': Plane,
  'ship': Ship,
  'truck': Truck,
  'fuel': Fuel,
  'navigation': Navigation,
  'compass': Compass,
  'map': Map,
  'route': Route,
  'location': MapPin,

  // Buildings
  'building': Building,

  // Nature
  'tree': TreePine,
  'mountain': Mountain,
  'sun': Sun,
  'moon': Moon,
  'cloud-rain': CloudRain,
  'cloud-snow': CloudSnow,
  'cloud-lightning': CloudLightning,
  'thermometer': Thermometer,
  'wind': Wind,
  'umbrella': Umbrella,
  'snowflake': Snowflake,
  'sunrise': Sunrise,
  'sunset': Sunset,

  // Analytics
  'activity': Activity,
  'bar-chart': BarChart,
  'bar-chart-2': BarChart2,
  'bar-chart-3': BarChart3,
  'pie-chart': PieChart,
  'line-chart': LineChart,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,

  // Finance
  'dollar': DollarSign,
  'credit-card': CreditCard,
  'coins': Coins,
  'wallet': Wallet,
  'receipt': Receipt,
  'calculator': Calculator,
  'percent': Percent,

  // Awards
  'award': Award,
  'crown': Crown,
  'gift': Gift,

  // Food
  'cake': Cake,
  'wine': Wine,
  'pizza': Pizza,
  'apple': Apple,
  'leaf': Leaf,
  'flower': Flower,
  'flower-2': Flower2,

  // Animals
  'bug': Bug,
  'fish': Fish,
  'bird': Bird,
  'cat': Cat,
  'dog': Dog,
};

// Helper function to get icon component
export const getProjectIcon = (iconName: string | undefined, size: number = 16, className?: string, style?: React.CSSProperties) => {
  const IconComponent = iconName ? iconMap[iconName.toLowerCase()] : iconMap['folder'];
  const FinalIcon = IconComponent || iconMap['folder']; // Fallback to folder icon

  return <FinalIcon size={size} className={className} style={style} />;
};

// Helper function to check if icon exists
export const hasIcon = (iconName: string): boolean => {
  return iconName ? !!iconMap[iconName.toLowerCase()] : false;
};

// Get list of available icon names
export const getAvailableIcons = (): string[] => {
  return Object.keys(iconMap);
};